sudo: required
dist: trusty
language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37
install:
  - scripts/travis.sh
  - make install
  - pip-accel install coveralls tox
  - pip-accel install -r requirements-checks.txt
script:
  - make check
  - make tox
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
