sudo: required
language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
install:
  - ./.travis.sh --install
  - make install
  - pip-accel install coveralls tox
  - pip-accel install -r requirements-checks.txt
script:
  - make check
  - make tox
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
