sudo: required
dist: bionic
language: python
matrix:
  include:
    - env: PYTHON=python2.6 TOXENV=py26
    - env: PYTHON=python2.7 TOXENV=py27
    - env: PYTHON=python3.4 TOXENV=py34
    - env: PYTHON=python3.5 TOXENV=py35
    - env: PYTHON=python3.6 TOXENV=py36
    - env: PYTHON=python3.7 TOXENV=py37
    - env: PYTHON=pypy TOXENV=pypy
install:
  - scripts/travis.sh
  - make install
  - pip install -r requirements-travis.txt
script:
  - make check
  - make tox
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
